# Generated by Django 5.0.6 on 2024-06-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0004_rename_timestamp_message_time_stamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
